#!/usr/bin/env node

/**
 * BlockPay Setup Script
 * Interactive setup wizard for BlockPay configuration
 */

import fs from 'fs'
import path from 'path'
import { fileURLToPath } from 'url'
import readline from 'readline'

const __filename = fileURLToPath(import.meta.url)
const __dirname = path.dirname(__filename)
const rootDir = path.resolve(__dirname, '..')

const rl = readline.createInterface({
  input: process.stdin,
  output: process.stdout
})

const question = (query) => new Promise((resolve) => rl.question(query, resolve))

console.log(`
╔════════════════════════════════════════════════════════════╗
║              BlockPay Setup Wizard                         ║
║         Production-Ready Crypto Payment System            ║
╚════════════════════════════════════════════════════════════╝
`)

async function setup() {
  const envPath = path.join(rootDir, '.env')
  const envExamplePath = path.join(rootDir, '.env.example')
  
  let envContent = ''
  
  // Check if .env exists
  if (fs.existsSync(envPath)) {
    envContent = fs.readFileSync(envPath, 'utf-8')
    console.log('📄 Found existing .env file\n')
    const overwrite = await question('Do you want to update it? (y/n): ')
    if (overwrite.toLowerCase() !== 'y') {
      console.log('\n✅ Setup cancelled. Your .env file remains unchanged.')
      rl.close()
      return
    }
  } else if (fs.existsSync(envExamplePath)) {
    envContent = fs.readFileSync(envExamplePath, 'utf-8')
    console.log('📄 Using .env.example as template\n')
  }

  console.log('\n🔧 Configuration Setup\n')
  console.log('Press Enter to skip optional fields\n')

  // ChangeNOW API Key
  console.log('1️⃣  ChangeNOW API Configuration')
  console.log('   Get your API key from: https://changenow.io/api\n')
  
  const apiKey = await question('ChangeNOW API Key (required): ')
  if (!apiKey) {
    console.log('⚠️  Warning: API key is required for production use\n')
  }
  
  const partnerId = await question('ChangeNOW Partner ID (optional, for affiliate tracking): ')

  // BlockPay Fees
  console.log('\n2️⃣  BlockPay Platform Fees')
  console.log('   Configure your platform fees\n')
  
  const feePercent = await question(`Platform Fee Percentage (default: 1.0%): `) || '0.01'
  const minFee = await question(`Minimum Fee in USD (default: $0.10): `) || '0.10'
  const maxFee = await question(`Maximum Fee in USD (default: 0 = no limit): `) || '0'
  
  // Fee Recipient
  console.log('\n3️⃣  Fee Collection')
  console.log('   Where should platform fees be collected?\n')
  
  const feeRecipient = await question('Fee Recipient Address (optional, can set later): ') || '0x0000000000000000000000000000000000000000'
  const feeChain = await question('Fee Collection Chain (default: ethereum): ') || 'ethereum'

  // Webhook
  console.log('\n4️⃣  Webhook Configuration')
  const webhookSecret = await question('Webhook Secret (optional, for ChangeNOW webhooks): ') || ''

  // Server
  console.log('\n5️⃣  Server Configuration')
  const port = await question('Server Port (default: 3001): ') || '3001'
  const nodeEnv = await question('Environment (development/production, default: production): ') || 'production'

  // Build .env content
  const newEnvContent = `# BlockPay Configuration
# Generated by setup wizard on ${new Date().toISOString()}

# ChangeNOW API Configuration
CHANGENOW_API_KEY=${apiKey}
CHANGENOW_PARTNER_ID=${partnerId}

# BlockPay Platform Fees
BLOCKPAY_FEE_PERCENT=${feePercent}
BLOCKPAY_MIN_FEE_USD=${minFee}
BLOCKPAY_MAX_FEE_USD=${maxFee}
BLOCKPAY_FEE_RECIPIENT=${feeRecipient}
BLOCKPAY_FEE_CHAIN=${feeChain}

# Webhook Configuration
WEBHOOK_SECRET=${webhookSecret}

# Server Configuration
PORT=${port}
NODE_ENV=${nodeEnv}

# Payment Request Settings
PAYMENT_REQUEST_EXPIRY_HOURS=1
MONITORING_INTERVAL_SECONDS=20

# Order Settings
ORDER_EXPIRY_HOURS=24
ORDER_STATUS_CHECK_INTERVAL=10
`

  // Write .env file
  fs.writeFileSync(envPath, newEnvContent)
  
  console.log('\n✅ Configuration saved to .env file\n')
  
  // Summary
  console.log('📋 Configuration Summary:')
  console.log(`   ChangeNOW API: ${apiKey ? '✅ Configured' : '❌ Not configured'}`)
  console.log(`   Platform Fee: ${(parseFloat(feePercent) * 100).toFixed(2)}%`)
  console.log(`   Minimum Fee: $${minFee}`)
  console.log(`   Maximum Fee: ${maxFee === '0' ? 'No limit' : '$' + maxFee}`)
  console.log(`   Fee Recipient: ${feeRecipient !== '0x0000000000000000000000000000000000000000' ? '✅ Configured' : '❌ Not configured'}`)
  console.log(`   Server Port: ${port}`)
  console.log(`   Environment: ${nodeEnv}`)
  
  if (!apiKey) {
    console.log('\n⚠️  IMPORTANT: You need to set CHANGENOW_API_KEY to use BlockPay in production!')
    console.log('   Get your API key from: https://changenow.io/api\n')
  }
  
  console.log('\n🚀 Next Steps:')
  console.log('   1. Review your .env file')
  console.log('   2. Start the server: npm start')
  console.log('   3. Check setup status: GET http://localhost:' + port + '/api/setup')
  console.log('\n✅ Setup complete!\n')
  
  rl.close()
}

setup().catch(error => {
  console.error('\n❌ Setup failed:', error.message)
  rl.close()
  process.exit(1)
})

